spring:
  datasource:
    url: jdbc:mysql://10.177.73.196/alg
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall  # sql监控和防火墙
      stat-view-servlet:  # 监控登录账号密码
        enabled: true
        login-username: admin
        login-password: admin

      web-stat-filter:  #网页监控
        url-pattern: /*
        enabled: true

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall: #防火墙
          enabled: true
      aop-patterns: com.dave.admin.*  # Spring监控

  jdbc:
    template:
      query-timeout: 3

# 配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml #全局配置文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名规则
